 name: Sync Fork

 on:
   schedule:
     - cron: '0 14 * * *' # every day at 2pm GMT / 9am eastern
   workflow_dispatch: # on button click

 jobs:
   sync:

     runs-on: ubuntu-latest

     steps:
       - uses: tgymnich/fork-sync@v1.9
         with:
           owner: fern-api
           base: main
           head: main
